# Generated by Django 4.2.29 on 2026-03-11 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisalert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crisisalert',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crisisalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
