# Generated by Django 4.2.29 on 2026-03-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_crisis_alert_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisalert',
            name='processing_notes',
            field=models.TextField(blank=True, default='', help_text='Notes recorded when acknowledging or resolving the alert'),
        ),
    ]
