# Generated by Django 4.2.29 on 2026-03-16 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood_score',
            field=models.IntegerField(help_text='Mood score from 1 (very low) to 10 (very high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', 'category'], name='idx_article_pub_category'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'session_id', 'created_at'], name='idx_chat_user_session'),
        ),
        migrations.AddIndex(
            model_name='crisisalert',
            index=models.Index(fields=['status', 'created_at'], name='idx_crisis_status_created'),
        ),
        migrations.AddIndex(
            model_name='encouragementmessage',
            index=models.Index(fields=['receiver', 'is_read'], name='idx_encourage_receiver_read'),
        ),
        migrations.AddIndex(
            model_name='recoverytask',
            index=models.Index(fields=['user', 'date'], name='idx_recovery_user_date'),
        ),
    ]
