# Generated by Django 4.2.29 on 2026-03-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_composite_indexes_and_validators'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recoverybadge',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supporterlink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='crisisalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['user', 'assessment_type', 'created_at'], name='idx_assess_user_type_created'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', 'created_at'], name='idx_mood_user_created'),
        ),
        migrations.AddConstraint(
            model_name='patientassignment',
            constraint=models.UniqueConstraint(fields=('patient', 'professional'), name='uniq_patient_professional'),
        ),
        migrations.AddConstraint(
            model_name='recoverybadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge_type'), name='uniq_user_badge_type'),
        ),
        migrations.AddConstraint(
            model_name='recoverytask',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'task_type'), name='uniq_user_date_tasktype'),
        ),
        migrations.AddConstraint(
            model_name='supporterlink',
            constraint=models.UniqueConstraint(fields=('supporter', 'patient'), name='uniq_supporter_patient'),
        ),
    ]
